import Head from 'next/head';
import styles from '../styles/Home.module.css';
import MuiNextLink from '@components/core-components/MuiNextLink';
import { Container, Stack } from '@mui/material';
import GetStarted from '@components/GetStarted';
import MintNFT from '@components/web3/mint-nft';
import { Button, Card, CardActions, CardContent, Input, Typography } from '@mui/material';
import Image from 'next/image';


export default function Home() {
  return (
    <Container>
      <Head id="home">
        <title>World of Men</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the
          
        </h1>
        <Image alt="sample NFT" src='/logo.png' width={831} height={172}/>
        <p className={styles.description}>
          <Stack spacing={1}>
            
          </Stack>
        </p>
        
        <MintNFT />
      </main>
    </Container>
  )
}
